### PR TITLE
fix(#37): add proper type inference to functional tool parameters t…

### LINKED ISSUE #37: Replace 'any' type in ToolInputParameters with proper generic constraints
**Description:**

The `ToolInputParameters` type uses `ZodObject<any>` which completely breaks type inference. When I define a tool with a Zod schema, the `execute` function gets `any` for the input parameter instead of the actual inferred type.

**Current code:**
```typescript
export type ToolInputParameters = undefined | ZodObject<any> | Schema;
```

**The problem:**
```typescript
const tool = new FunctionTool({
  parameters: z.object({
    studentId: z.number(),
    name: z.string(),
  }),
  execute: async (input) => {
    // input is 'any' here - no autocomplete, no type checking
    input.studnetId; // typo, but no error
    input.whatever;  // doesn't exist, but no error
    return input;
  },
});
```

The Zod schema provides type information, but it's not being used. This forces us to write separate typed functions and pass them to `execute`, duplicating type definitions.

**What I expected:**
```typescript
execute: async (input) => {
  // should be: { studentId: number, name: string }
  input.studentId; // should autocomplete
  input.whatever;  // should error
}
```

**Suggested fix:**

Replace the `any` with proper Zod generics:
```typescript
export type ToolInputParameters = 
  | undefined 
  | ZodObject<ZodRawShape, UnknownKeysParam, ZodTypeAny> 
  | Schema;
```

Then let the `ToolExecuteArgument` type do proper inference from the schema shape.

**Environment:**
- @google/adk: 0.2.0
- TypeScript: 5.3.0
- Runtime: Bun

Currently we're defining types twice (in schema and in function) which defeats the purpose of schema-driven development.

### PR DESCRIPTION
**Pull request by jagadhis**
**Summary:**

This PR replaces `any` types in `FunctionTool` with proper Zod generics, enabling automatic type inference from schemas to execute functions.

## Changes

- Replaced `ZodObject<any>` with `ZodObject<ZodRawShape>` in `ToolInputParameters`
- Updated `ToolExecuteArgument` to properly infer types using `infer T, U, V`
- Removed unnecessary `any` cast in constructor

## Impact
```typescript
const tool = new FunctionTool({
  parameters: z.object({ 
    studentId: z.number(),
    name: z.string()
  }),
  execute: async ({ studentId, name }) => {
    // studentId and name are now automatically typed from schema
    return { studentId, name };
  },
});
```

## Testing

Added test to verify type inference works without explicit type annotations. All existing tests continue to pass.

## Benefits
- Automatic type inference from Zod schemas
- Full autocomplete/IntelliSense support
- Compile-time type checking

Fixes #37

### CODE REVIEW

File: core/test/tools/function_tool_test.ts [hunk 1]
```diff
@@ -4,9 +4,10 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
-import {FunctionTool, ToolContext} from '@google/adk';
-import {Type} from '@google/genai';
-import {z} from 'zod';
+import { FunctionTool, ToolContext } from '@google/adk'
+import { Type } from '@google/genai'
+import { beforeEach, describe, expect, it } from 'vitest'
```
Comment (kalenkevich) [inline core/test/tools/function_tool_test.ts]: Please remove this line

Long story short - we need to support tests in our google internal build where `beforeEach, describe, expect, it` are available globally in the test file.

Thanks!

**Review by kalenkevich — APPROVED** [review]

**Comment by jagadhis** [comment]
@kalenkevich Thanks for the approval! The comment has been resolved and the branch is now rebased with main. can you re-approve it again
